# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MokZhiZhuan\OneDrive - WINSYS TECHNOLOGY PTE LTD\Desktop\Greyform\Python_Application\UI_Design\createacc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 50, 171, 71))
        self.label.setStyleSheet("color:rgb(225, 225, 225); font-size:28pt;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 101, 31))
        self.label_2.setStyleSheet("font-size:15pt; color:rgb(255, 0, 127)")
        self.label_2.setObjectName("label_2")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(200, 150, 211, 51))
        self.email.setStyleSheet("font-size:14pt; color:rgb(243, 243, 243)")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(200, 250, 211, 51))
        self.password.setStyleSheet("font-size:14pt; color:rgb(243, 243, 243)")
        self.password.setText("")
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 260, 111, 31))
        self.label_3.setStyleSheet("font-size:15pt; color:rgb(255, 0, 127)")
        self.label_3.setObjectName("label_3")
        self.signupbutton = QtWidgets.QPushButton(Dialog)
        self.signupbutton.setGeometry(QtCore.QRect(270, 420, 141, 41))
        self.signupbutton.setStyleSheet("background-color: rgb(167, 168, 167); font-size:14pt; color:rgb(255, 255, 255)")
        self.signupbutton.setObjectName("signupbutton")
        self.backbutton = QtWidgets.QPushButton(Dialog)
        self.backbutton.setGeometry(QtCore.QRect(100, 420, 141, 41))
        self.backbutton.setStyleSheet("background-color: rgb(167, 168, 167); font-size:14pt; color:rgb(255, 255, 255)")
        self.backbutton.setObjectName("backbutton")
        self.confirmpass = QtWidgets.QLineEdit(Dialog)
        self.confirmpass.setGeometry(QtCore.QRect(200, 350, 211, 51))
        self.confirmpass.setStyleSheet("font-size:14pt; color:rgb(243, 243, 243)")
        self.confirmpass.setText("")
        self.confirmpass.setObjectName("confirmpass")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 360, 151, 31))
        self.label_4.setStyleSheet("font-size:15pt; color:rgb(255, 0, 127)")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign up"))
        self.label_2.setText(_translate("Dialog", "Email"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.signupbutton.setText(_translate("Dialog", "Sign up"))
        self.backbutton.setText(_translate("Dialog", "Back"))
        self.label_4.setText(_translate("Dialog", "Confirm Pass"))
