# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainframe.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QHBoxLayout,
    QLabel, QListView, QMainWindow, QPushButton,
    QSizePolicy, QStackedWidget, QStatusBar, QVBoxLayout,
    QWidget)
import Cover_1.stl_rc
import square_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(-10, 20, 1980, 1080))
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(11)
        self.stackedWidget.setFont(font)
        self.mainmenu = QWidget()
        self.mainmenu.setObjectName(u"mainmenu")
        sizePolicy.setHeightForWidth(self.mainmenu.sizePolicy().hasHeightForWidth())
        self.mainmenu.setSizePolicy(sizePolicy)
        self.QTitle = QLabel(self.mainmenu)
        self.QTitle.setObjectName(u"QTitle")
        self.QTitle.setGeometry(QRect(420, 530, 1139, 55))
        self.QTitle.setScaledContents(False)
        self.QTitle.setAlignment(Qt.AlignCenter)
        self.menuStartButton = QPushButton(self.mainmenu)
        self.menuStartButton.setObjectName(u"menuStartButton")
        self.menuStartButton.setGeometry(QRect(720, 980, 240, 25))
        self.menuStartButton.setCheckable(False)
        self.menuCloseButton = QPushButton(self.mainmenu)
        self.menuCloseButton.setObjectName(u"menuCloseButton")
        self.menuCloseButton.setGeometry(QRect(1000, 980, 240, 25))
        self.menuCloseButton.setCheckable(False)
        self.stackedWidget.addWidget(self.mainmenu)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.Selectivefilelistview = QListView(self.page)
        self.Selectivefilelistview.setObjectName(u"Selectivefilelistview")
        self.Selectivefilelistview.setGeometry(QRect(100, 80, 431, 861))
        self.NextButton_Page_2 = QPushButton(self.page)
        self.NextButton_Page_2.setObjectName(u"NextButton_Page_2")
        self.NextButton_Page_2.setGeometry(QRect(360, 980, 101, 25))
        self.BacktoMenuButton = QPushButton(self.page)
        self.BacktoMenuButton.setObjectName(u"BacktoMenuButton")
        self.BacktoMenuButton.setGeometry(QRect(210, 980, 121, 25))
        self.horizontalLayoutWidget_2 = QWidget(self.page)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(840, 90, 1061, 841))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pyvistaframe = QFrame(self.horizontalLayoutWidget_2)
        self.pyvistaframe.setObjectName(u"pyvistaframe")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pyvistaframe.sizePolicy().hasHeightForWidth())
        self.pyvistaframe.setSizePolicy(sizePolicy1)
        self.pyvistaframe.setFrameShape(QFrame.StyledPanel)
        self.pyvistaframe.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_2.addWidget(self.pyvistaframe)

        self.FilePathButton = QPushButton(self.page)
        self.FilePathButton.setObjectName(u"FilePathButton")
        self.FilePathButton.setGeometry(QRect(100, 980, 89, 25))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.Itemlabel_Page_2 = QLabel(self.page_2)
        self.Itemlabel_Page_2.setObjectName(u"Itemlabel_Page_2")
        self.Itemlabel_Page_2.setGeometry(QRect(450, 30, 1079, 170))
        self.BackButton_Page_1 = QPushButton(self.page_2)
        self.BackButton_Page_1.setObjectName(u"BackButton_Page_1")
        self.BackButton_Page_1.setGeometry(QRect(220, 980, 80, 25))
        self.NextButton_Page_3 = QPushButton(self.page_2)
        self.NextButton_Page_3.setObjectName(u"NextButton_Page_3")
        self.NextButton_Page_3.setGeometry(QRect(100, 980, 80, 25))
        self.horizontalLayoutWidget = QWidget(self.page_2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(660, 210, 1221, 691))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pyvistaframe_2 = QFrame(self.horizontalLayoutWidget)
        self.pyvistaframe_2.setObjectName(u"pyvistaframe_2")
        self.pyvistaframe_2.setFrameShape(QFrame.StyledPanel)
        self.pyvistaframe_2.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_4.addWidget(self.pyvistaframe_2)

        self.seq1Button = QPushButton(self.page_2)
        self.seq1Button.setObjectName(u"seq1Button")
        self.seq1Button.setGeometry(QRect(100, 210, 281, 171))
        font1 = QFont()
        font1.setPointSize(30)
        self.seq1Button.setFont(font1)
        self.seq2Button = QPushButton(self.page_2)
        self.seq2Button.setObjectName(u"seq2Button")
        self.seq2Button.setGeometry(QRect(100, 440, 281, 171))
        self.seq2Button.setFont(font1)
        self.seq3Button = QPushButton(self.page_2)
        self.seq3Button.setObjectName(u"seq3Button")
        self.seq3Button.setGeometry(QRect(100, 660, 281, 171))
        self.seq3Button.setFont(font1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        sizePolicy.setHeightForWidth(self.page_3.sizePolicy().hasHeightForWidth())
        self.page_3.setSizePolicy(sizePolicy)
        self.Ygroupbox = QGroupBox(self.page_3)
        self.Ygroupbox.setObjectName(u"Ygroupbox")
        self.Ygroupbox.setGeometry(QRect(1700, 940, 171, 51))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Ygroupbox.sizePolicy().hasHeightForWidth())
        self.Ygroupbox.setSizePolicy(sizePolicy2)
        self.titleYlabel = QLabel(self.Ygroupbox)
        self.titleYlabel.setObjectName(u"titleYlabel")
        self.titleYlabel.setGeometry(QRect(10, 20, 61, 17))
        self.Ylabel = QLabel(self.Ygroupbox)
        self.Ylabel.setObjectName(u"Ylabel")
        self.Ylabel.setGeometry(QRect(80, 10, 91, 31))
        self.Xgroupbox = QGroupBox(self.page_3)
        self.Xgroupbox.setObjectName(u"Xgroupbox")
        self.Xgroupbox.setGeometry(QRect(1700, 860, 171, 61))
        self.titleXlabel = QLabel(self.Xgroupbox)
        self.titleXlabel.setObjectName(u"titleXlabel")
        self.titleXlabel.setGeometry(QRect(10, 20, 71, 17))
        self.Xlabel = QLabel(self.Xgroupbox)
        self.Xlabel.setObjectName(u"Xlabel")
        self.Xlabel.setGeometry(QRect(80, 20, 91, 31))
        self.BackButton_Page_2 = QPushButton(self.page_3)
        self.BackButton_Page_2.setObjectName(u"BackButton_Page_2")
        self.BackButton_Page_2.setGeometry(QRect(590, 980, 80, 25))
        self.Confirmbutton = QPushButton(self.page_3)
        self.Confirmbutton.setObjectName(u"Confirmbutton")
        self.Confirmbutton.setGeometry(QRect(430, 980, 80, 25))
        self.Itemlabel_Page_3 = QLabel(self.page_3)
        self.Itemlabel_Page_3.setObjectName(u"Itemlabel_Page_3")
        self.Itemlabel_Page_3.setGeometry(QRect(480, 910, 751, 21))
        self.Seqlabel = QLabel(self.page_3)
        self.Seqlabel.setObjectName(u"Seqlabel")
        self.Seqlabel.setGeometry(QRect(480, 850, 751, 21))
        self.verticalLayoutWidget = QWidget(self.page_3)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(160, 20, 1601, 801))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.verticalLayoutWidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)

        self.verticalLayout.addWidget(self.frame)

        self.Xgroupbox_2 = QGroupBox(self.page_3)
        self.Xgroupbox_2.setObjectName(u"Xgroupbox_2")
        self.Xgroupbox_2.setGeometry(QRect(1490, 860, 171, 61))
        self.titleXlabel_2 = QLabel(self.Xgroupbox_2)
        self.titleXlabel_2.setObjectName(u"titleXlabel_2")
        self.titleXlabel_2.setGeometry(QRect(10, 20, 71, 17))
        self.Xlabel_2 = QLabel(self.Xgroupbox_2)
        self.Xlabel_2.setObjectName(u"Xlabel_2")
        self.Xlabel_2.setGeometry(QRect(80, 20, 91, 31))
        self.Ygroupbox_2 = QGroupBox(self.page_3)
        self.Ygroupbox_2.setObjectName(u"Ygroupbox_2")
        self.Ygroupbox_2.setGeometry(QRect(1500, 940, 171, 51))
        sizePolicy2.setHeightForWidth(self.Ygroupbox_2.sizePolicy().hasHeightForWidth())
        self.Ygroupbox_2.setSizePolicy(sizePolicy2)
        self.titleYlabel_2 = QLabel(self.Ygroupbox_2)
        self.titleYlabel_2.setObjectName(u"titleYlabel_2")
        self.titleYlabel_2.setGeometry(QRect(10, 20, 61, 17))
        self.Ylabel_2 = QLabel(self.Ygroupbox_2)
        self.Ylabel_2.setObjectName(u"Ylabel_2")
        self.Ylabel_2.setGeometry(QRect(80, 10, 91, 31))
        self.displaybeforelabel = QLabel(self.page_3)
        self.displaybeforelabel.setObjectName(u"displaybeforelabel")
        self.displaybeforelabel.setGeometry(QRect(1530, 840, 101, 17))
        self.label_2 = QLabel(self.page_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1740, 830, 101, 17))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.HomeButton = QPushButton(self.page_4)
        self.HomeButton.setObjectName(u"HomeButton")
        self.HomeButton.setGeometry(QRect(130, 410, 481, 271))
        font2 = QFont()
        font2.setPointSize(40)
        self.HomeButton.setFont(font2)
        self.EnableRobotButton = QPushButton(self.page_4)
        self.EnableRobotButton.setObjectName(u"EnableRobotButton")
        self.EnableRobotButton.setGeometry(QRect(960, 410, 481, 271))
        self.EnableRobotButton.setFont(font2)
        self.ConfirmackButton = QPushButton(self.page_4)
        self.ConfirmackButton.setObjectName(u"ConfirmackButton")
        self.ConfirmackButton.setGeometry(QRect(950, 760, 481, 271))
        self.ConfirmackButton.setFont(font2)
        self.CloseButton = QPushButton(self.page_4)
        self.CloseButton.setObjectName(u"CloseButton")
        self.CloseButton.setGeometry(QRect(130, 740, 481, 271))
        self.CloseButton.setFont(font2)
        self.MarkingButton = QPushButton(self.page_4)
        self.MarkingButton.setObjectName(u"MarkingButton")
        self.MarkingButton.setGeometry(QRect(550, 70, 481, 271))
        self.MarkingButton.setFont(font2)
        self.SettingButton = QPushButton(self.page_4)
        self.SettingButton.setObjectName(u"SettingButton")
        self.SettingButton.setGeometry(QRect(1810, 20, 89, 25))
        self.stackedWidget.addWidget(self.page_4)
        self.settingpage = QWidget()
        self.settingpage.setObjectName(u"settingpage")
        self.verticalLayoutWidget_2 = QWidget(self.settingpage)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(60, 30, 1721, 941))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.labeltitlsetting = QLabel(self.verticalLayoutWidget_2)
        self.labeltitlsetting.setObjectName(u"labeltitlsetting")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.labeltitlsetting.sizePolicy().hasHeightForWidth())
        self.labeltitlsetting.setSizePolicy(sizePolicy3)
        font3 = QFont()
        font3.setPointSize(20)
        font3.setBold(True)
        self.labeltitlsetting.setFont(font3)
        self.labeltitlsetting.setTextFormat(Qt.AutoText)
        self.labeltitlsetting.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.labeltitlsetting)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.WifiButton = QPushButton(self.verticalLayoutWidget_2)
        self.WifiButton.setObjectName(u"WifiButton")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.WifiButton.sizePolicy().hasHeightForWidth())
        self.WifiButton.setSizePolicy(sizePolicy4)

        self.verticalLayout_4.addWidget(self.WifiButton)

        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.serviceIPAddressButton = QPushButton(self.verticalLayoutWidget_2)
        self.serviceIPAddressButton.setObjectName(u"serviceIPAddressButton")

        self.verticalLayout_5.addWidget(self.serviceIPAddressButton)

        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.ServicesButton = QPushButton(self.verticalLayoutWidget_2)
        self.ServicesButton.setObjectName(u"ServicesButton")

        self.verticalLayout_6.addWidget(self.ServicesButton)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.UserButton = QPushButton(self.verticalLayoutWidget_2)
        self.UserButton.setObjectName(u"UserButton")

        self.verticalLayout_3.addWidget(self.UserButton)

        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.PowerButton = QPushButton(self.verticalLayoutWidget_2)
        self.PowerButton.setObjectName(u"PowerButton")

        self.verticalLayout_7.addWidget(self.PowerButton)

        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.AboutButton = QPushButton(self.verticalLayoutWidget_2)
        self.AboutButton.setObjectName(u"AboutButton")

        self.verticalLayout_8.addWidget(self.AboutButton)

        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.MarkingbackUIButton = QPushButton(self.verticalLayoutWidget_2)
        self.MarkingbackUIButton.setObjectName(u"MarkingbackUIButton")

        self.verticalLayout_9.addWidget(self.MarkingbackUIButton)

        self.verticalLayout_10 = QVBoxLayout()
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")

        self.verticalLayout_9.addLayout(self.verticalLayout_10)


        self.verticalLayout_8.addLayout(self.verticalLayout_9)


        self.verticalLayout_7.addLayout(self.verticalLayout_8)


        self.verticalLayout_3.addLayout(self.verticalLayout_7)


        self.verticalLayout_6.addLayout(self.verticalLayout_3)


        self.verticalLayout_5.addLayout(self.verticalLayout_6)


        self.verticalLayout_4.addLayout(self.verticalLayout_5)


        self.horizontalLayout_3.addLayout(self.verticalLayout_4)

        self.verticalLayout_11 = QVBoxLayout()
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")

        self.horizontalLayout_3.addLayout(self.verticalLayout_11)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.verticalLayout_2.setStretch(1, 1)
        self.stackedWidget.addWidget(self.settingpage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"mainframe", None))
        self.QTitle.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:36pt;\">GRAYFORM UI</span></p></body></html>", None))
        self.menuStartButton.setText(QCoreApplication.translate("MainWindow", u"Click to Continue", None))
        self.menuCloseButton.setText(QCoreApplication.translate("MainWindow", u"Click to Close the Window", None))
        self.NextButton_Page_2.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.BacktoMenuButton.setText(QCoreApplication.translate("MainWindow", u"Back To Menu", None))
        self.FilePathButton.setText(QCoreApplication.translate("MainWindow", u"File_Path", None))
        self.Itemlabel_Page_2.setText(QCoreApplication.translate("MainWindow", u"Product :", None))
        self.BackButton_Page_1.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.NextButton_Page_3.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.seq1Button.setText(QCoreApplication.translate("MainWindow", u"Sequence 1", None))
        self.seq2Button.setText(QCoreApplication.translate("MainWindow", u"Sequence 2", None))
        self.seq3Button.setText(QCoreApplication.translate("MainWindow", u"Sequence 3", None))
        self.Ygroupbox.setTitle("")
        self.titleYlabel.setText(QCoreApplication.translate("MainWindow", u"Height:", None))
        self.Ylabel.setText(QCoreApplication.translate("MainWindow", u"800", None))
        self.Xgroupbox.setTitle("")
        self.titleXlabel.setText(QCoreApplication.translate("MainWindow", u"Width:", None))
        self.Xlabel.setText(QCoreApplication.translate("MainWindow", u"800", None))
        self.BackButton_Page_2.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.Confirmbutton.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.Itemlabel_Page_3.setText(QCoreApplication.translate("MainWindow", u"Product:", None))
        self.Seqlabel.setText(QCoreApplication.translate("MainWindow", u"Sequence:", None))
        self.Xgroupbox_2.setTitle("")
        self.titleXlabel_2.setText(QCoreApplication.translate("MainWindow", u"Width:", None))
        self.Xlabel_2.setText(QCoreApplication.translate("MainWindow", u"800", None))
        self.Ygroupbox_2.setTitle("")
        self.titleYlabel_2.setText(QCoreApplication.translate("MainWindow", u"Height:", None))
        self.Ylabel_2.setText(QCoreApplication.translate("MainWindow", u"800", None))
        self.displaybeforelabel.setText(QCoreApplication.translate("MainWindow", u"Before Display", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"After Display", None))
        self.HomeButton.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.EnableRobotButton.setText(QCoreApplication.translate("MainWindow", u"Enable Robot", None))
        self.ConfirmackButton.setText(QCoreApplication.translate("MainWindow", u"Acknowledge", None))
        self.CloseButton.setText(QCoreApplication.translate("MainWindow", u"Abort/Close", None))
        self.MarkingButton.setText(QCoreApplication.translate("MainWindow", u"Back to Marking", None))
        self.SettingButton.setText(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.labeltitlsetting.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.WifiButton.setText(QCoreApplication.translate("MainWindow", u"Wifi", None))
        self.serviceIPAddressButton.setText(QCoreApplication.translate("MainWindow", u"Service IP Address", None))
        self.ServicesButton.setText(QCoreApplication.translate("MainWindow", u"Services", None))
        self.UserButton.setText(QCoreApplication.translate("MainWindow", u"User", None))
        self.PowerButton.setText(QCoreApplication.translate("MainWindow", u"Power/ShutDown/Restart", None))
        self.AboutButton.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.MarkingbackUIButton.setText(QCoreApplication.translate("MainWindow", u"Back to Marking", None))
    # retranslateUi

