# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'setting.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QStackedWidget, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(694, 548)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.labeltitlsetting = QLabel(Form)
        self.labeltitlsetting.setObjectName(u"labeltitlsetting")
        self.labeltitlsetting.setGeometry(QRect(0, 10, 689, 32))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.labeltitlsetting.sizePolicy().hasHeightForWidth())
        self.labeltitlsetting.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.labeltitlsetting.setFont(font)
        self.labeltitlsetting.setTextFormat(Qt.AutoText)
        self.labeltitlsetting.setAlignment(Qt.AlignCenter)
        self.settinglayoutWidget = QWidget(Form)
        self.settinglayoutWidget.setObjectName(u"settinglayoutWidget")
        self.settinglayoutWidget.setGeometry(QRect(0, 50, 689, 481))
        self.horizontalLayout_2 = QHBoxLayout(self.settinglayoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.HomeButton = QPushButton(self.settinglayoutWidget)
        self.HomeButton.setObjectName(u"HomeButton")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.HomeButton.sizePolicy().hasHeightForWidth())
        self.HomeButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.HomeButton)

        self.WifiButton = QPushButton(self.settinglayoutWidget)
        self.WifiButton.setObjectName(u"WifiButton")
        sizePolicy2.setHeightForWidth(self.WifiButton.sizePolicy().hasHeightForWidth())
        self.WifiButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.WifiButton)

        self.serviceIPAddressButton = QPushButton(self.settinglayoutWidget)
        self.serviceIPAddressButton.setObjectName(u"serviceIPAddressButton")
        sizePolicy2.setHeightForWidth(self.serviceIPAddressButton.sizePolicy().hasHeightForWidth())
        self.serviceIPAddressButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.serviceIPAddressButton)

        self.ServicesButton = QPushButton(self.settinglayoutWidget)
        self.ServicesButton.setObjectName(u"ServicesButton")
        sizePolicy2.setHeightForWidth(self.ServicesButton.sizePolicy().hasHeightForWidth())
        self.ServicesButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.ServicesButton)

        self.UserButton = QPushButton(self.settinglayoutWidget)
        self.UserButton.setObjectName(u"UserButton")
        sizePolicy2.setHeightForWidth(self.UserButton.sizePolicy().hasHeightForWidth())
        self.UserButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.UserButton)

        self.PowerButton = QPushButton(self.settinglayoutWidget)
        self.PowerButton.setObjectName(u"PowerButton")
        sizePolicy2.setHeightForWidth(self.PowerButton.sizePolicy().hasHeightForWidth())
        self.PowerButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.PowerButton)

        self.AboutButton = QPushButton(self.settinglayoutWidget)
        self.AboutButton.setObjectName(u"AboutButton")
        sizePolicy2.setHeightForWidth(self.AboutButton.sizePolicy().hasHeightForWidth())
        self.AboutButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.AboutButton)

        self.MarkingbackButton = QPushButton(self.settinglayoutWidget)
        self.MarkingbackButton.setObjectName(u"MarkingbackButton")
        sizePolicy2.setHeightForWidth(self.MarkingbackButton.sizePolicy().hasHeightForWidth())
        self.MarkingbackButton.setSizePolicy(sizePolicy2)

        self.verticalLayout_2.addWidget(self.MarkingbackButton)

        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(7, 1)

        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.maintitlelabel = QLabel(self.settinglayoutWidget)
        self.maintitlelabel.setObjectName(u"maintitlelabel")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.maintitlelabel.sizePolicy().hasHeightForWidth())
        self.maintitlelabel.setSizePolicy(sizePolicy3)
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.maintitlelabel.setFont(font1)
        self.maintitlelabel.setWordWrap(True)

        self.verticalLayout_4.addWidget(self.maintitlelabel)

        self.stackedWidgetsetting = QStackedWidget(self.settinglayoutWidget)
        self.stackedWidgetsetting.setObjectName(u"stackedWidgetsetting")
        self.settingHomepage = QWidget()
        self.settingHomepage.setObjectName(u"settingHomepage")
        self.layoutWidgethome = QWidget(self.settingHomepage)
        self.layoutWidgethome.setObjectName(u"layoutWidgethome")
        self.layoutWidgethome.setGeometry(QRect(10, 130, 319, 111))
        self.horizontalLayout = QHBoxLayout(self.layoutWidgethome)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.colortitlelabel = QLabel(self.layoutWidgethome)
        self.colortitlelabel.setObjectName(u"colortitlelabel")

        self.horizontalLayout.addWidget(self.colortitlelabel)

        self.themebox = QComboBox(self.layoutWidgethome)
        self.themebox.addItem("")
        self.themebox.addItem("")
        self.themebox.addItem("")
        self.themebox.addItem("")
        self.themebox.setObjectName(u"themebox")

        self.horizontalLayout.addWidget(self.themebox)

        self.restoreDefaultsButton = QPushButton(self.settingHomepage)
        self.restoreDefaultsButton.setObjectName(u"restoreDefaultsButton")
        self.restoreDefaultsButton.setGeometry(QRect(10, 400, 319, 25))
        self.stackedWidgetsetting.addWidget(self.settingHomepage)
        self.wifipage = QWidget()
        self.wifipage.setObjectName(u"wifipage")
        self.interface_label = QLabel(self.wifipage)
        self.interface_label.setObjectName(u"interface_label")
        self.interface_label.setGeometry(QRect(10, 10, 319, 17))
        self.interface_label.setWordWrap(True)
        self.treeWidget = QTreeWidget(self.wifipage)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(10, 40, 319, 399))
        self.stackedWidgetsetting.addWidget(self.wifipage)
        self.serviceipaddresspage = QWidget()
        self.serviceipaddresspage.setObjectName(u"serviceipaddresspage")
        self.ip_label = QLabel(self.serviceipaddresspage)
        self.ip_label.setObjectName(u"ip_label")
        self.ip_label.setGeometry(QRect(0, 10, 309, 197))
        self.ip_label.setWordWrap(True)
        self.Portnumipadd = QLabel(self.serviceipaddresspage)
        self.Portnumipadd.setObjectName(u"Portnumipadd")
        self.Portnumipadd.setGeometry(QRect(10, 240, 309, 196))
        font2 = QFont()
        font2.setPointSize(15)
        self.Portnumipadd.setFont(font2)
        self.Portnumipadd.setWordWrap(True)
        self.stackedWidgetsetting.addWidget(self.serviceipaddresspage)
        self.servicespage = QWidget()
        self.servicespage.setObjectName(u"servicespage")
        self.layoutWidgetservicestextsize = QWidget(self.servicespage)
        self.layoutWidgetservicestextsize.setObjectName(u"layoutWidgetservicestextsize")
        self.layoutWidgetservicestextsize.setGeometry(QRect(10, 110, 319, 36))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidgetservicestextsize)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.Textsizelab = QLabel(self.layoutWidgetservicestextsize)
        self.Textsizelab.setObjectName(u"Textsizelab")
        self.Textsizelab.setFont(font2)

        self.horizontalLayout_4.addWidget(self.Textsizelab)

        self.Text_size = QComboBox(self.layoutWidgetservicestextsize)
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.addItem("")
        self.Text_size.setObjectName(u"Text_size")
        self.Text_size.setFont(font2)

        self.horizontalLayout_4.addWidget(self.Text_size)

        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.host = QLabel(self.servicespage)
        self.host.setObjectName(u"host")
        self.host.setGeometry(QRect(10, 27, 319, 36))
        self.host.setFont(font2)
        self.layoutWidgetservicesresolution = QWidget(self.servicespage)
        self.layoutWidgetservicesresolution.setObjectName(u"layoutWidgetservicesresolution")
        self.layoutWidgetservicesresolution.setGeometry(QRect(10, 152, 319, 36))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidgetservicesresolution)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.Resolutionlab = QLabel(self.layoutWidgetservicesresolution)
        self.Resolutionlab.setObjectName(u"Resolutionlab")
        self.Resolutionlab.setFont(font2)

        self.horizontalLayout_3.addWidget(self.Resolutionlab)

        self.resolutioncomboBox = QComboBox(self.layoutWidgetservicesresolution)
        self.resolutioncomboBox.addItem("")
        self.resolutioncomboBox.addItem("")
        self.resolutioncomboBox.addItem("")
        self.resolutioncomboBox.addItem("")
        self.resolutioncomboBox.addItem("")
        self.resolutioncomboBox.setObjectName(u"resolutioncomboBox")
        self.resolutioncomboBox.setFont(font2)

        self.horizontalLayout_3.addWidget(self.resolutioncomboBox)

        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.layoutWidgetservicescountryGMT = QWidget(self.servicespage)
        self.layoutWidgetservicescountryGMT.setObjectName(u"layoutWidgetservicescountryGMT")
        self.layoutWidgetservicescountryGMT.setGeometry(QRect(10, 319, 319, 35))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidgetservicescountryGMT)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.setcountryGMT = QLabel(self.layoutWidgetservicescountryGMT)
        self.setcountryGMT.setObjectName(u"setcountryGMT")
        self.setcountryGMT.setFont(font2)

        self.horizontalLayout_6.addWidget(self.setcountryGMT)

        self.country = QComboBox(self.layoutWidgetservicescountryGMT)
        self.country.setObjectName(u"country")
        self.country.setFont(font2)

        self.horizontalLayout_6.addWidget(self.country)

        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.SystemDate = QLabel(self.servicespage)
        self.SystemDate.setObjectName(u"SystemDate")
        self.SystemDate.setGeometry(QRect(10, 194, 319, 35))
        self.SystemDate.setFont(font2)
        self.layoutWidgetservicessetpass = QWidget(self.servicespage)
        self.layoutWidgetservicessetpass.setObjectName(u"layoutWidgetservicessetpass")
        self.layoutWidgetservicessetpass.setGeometry(QRect(10, 360, 319, 36))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidgetservicessetpass)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.setpassword = QLabel(self.layoutWidgetservicessetpass)
        self.setpassword.setObjectName(u"setpassword")
        self.setpassword.setFont(font2)

        self.horizontalLayout_5.addWidget(self.setpassword)

        self.PasslineEdit = QLineEdit(self.layoutWidgetservicessetpass)
        self.PasslineEdit.setObjectName(u"PasslineEdit")
        font3 = QFont()
        font3.setPointSize(15)
        font3.setStyleStrategy(QFont.PreferDefault)
        self.PasslineEdit.setFont(font3)
        self.PasslineEdit.setEchoMode(QLineEdit.Password)

        self.horizontalLayout_5.addWidget(self.PasslineEdit)

        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.Systemtime = QLabel(self.servicespage)
        self.Systemtime.setObjectName(u"Systemtime")
        self.Systemtime.setGeometry(QRect(10, 277, 319, 36))
        self.Systemtime.setFont(font2)
        self.SystemMemory = QLabel(self.servicespage)
        self.SystemMemory.setObjectName(u"SystemMemory")
        self.SystemMemory.setGeometry(QRect(10, 235, 319, 36))
        self.SystemMemory.setFont(font2)
        self.Port = QLabel(self.servicespage)
        self.Port.setObjectName(u"Port")
        self.Port.setGeometry(QRect(10, 69, 319, 35))
        self.Port.setFont(font2)
        self.stackedWidgetsetting.addWidget(self.servicespage)
        self.UserPage = QWidget()
        self.UserPage.setObjectName(u"UserPage")
        self.stackedWidgetsetting.addWidget(self.UserPage)
        self.AboutPage = QWidget()
        self.AboutPage.setObjectName(u"AboutPage")
        self.version_label = QLabel(self.AboutPage)
        self.version_label.setObjectName(u"version_label")
        self.version_label.setGeometry(QRect(10, 310, 319, 90))
        self.titlelabel = QLabel(self.AboutPage)
        self.titlelabel.setObjectName(u"titlelabel")
        self.titlelabel.setGeometry(QRect(10, 117, 319, 91))
        self.author_label = QLabel(self.AboutPage)
        self.author_label.setObjectName(u"author_label")
        self.author_label.setGeometry(QRect(10, 21, 319, 90))
        self.info_label = QLabel(self.AboutPage)
        self.info_label.setObjectName(u"info_label")
        self.info_label.setGeometry(QRect(10, 214, 319, 90))
        self.info_label.setWordWrap(True)
        self.stackedWidgetsetting.addWidget(self.AboutPage)
        self.RestartPowerOffPage = QWidget()
        self.RestartPowerOffPage.setObjectName(u"RestartPowerOffPage")
        self.stackedWidgetsetting.addWidget(self.RestartPowerOffPage)

        self.verticalLayout_4.addWidget(self.stackedWidgetsetting)

        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)

        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.labeltitlsetting.setText(QCoreApplication.translate("Form", u"Settings", None))
        self.HomeButton.setText(QCoreApplication.translate("Form", u"Home", None))
        self.WifiButton.setText(QCoreApplication.translate("Form", u"Wifi", None))
        self.serviceIPAddressButton.setText(QCoreApplication.translate("Form", u"Service IP Address", None))
        self.ServicesButton.setText(QCoreApplication.translate("Form", u"Services and Resolution", None))
        self.UserButton.setText(QCoreApplication.translate("Form", u"User", None))
        self.PowerButton.setText(QCoreApplication.translate("Form", u"Power/ShutDown/Restart", None))
        self.AboutButton.setText(QCoreApplication.translate("Form", u"About", None))
        self.MarkingbackButton.setText(QCoreApplication.translate("Form", u"Back to Marking Button UI", None))
        self.maintitlelabel.setText("")
        self.colortitlelabel.setText(QCoreApplication.translate("Form", u"Color Theme", None))
        self.themebox.setItemText(0, QCoreApplication.translate("Form", u"Gray", None))
        self.themebox.setItemText(1, QCoreApplication.translate("Form", u"Black", None))
        self.themebox.setItemText(2, QCoreApplication.translate("Form", u"Light", None))
        self.themebox.setItemText(3, QCoreApplication.translate("Form", u"Other Color", None))

        self.restoreDefaultsButton.setText(QCoreApplication.translate("Form", u"Restore to Defaults", None))
        self.interface_label.setText("")
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("Form", u"Signal Strength", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("Form", u"SSID", None));
        self.ip_label.setText("")
        self.Portnumipadd.setText("")
        self.Textsizelab.setText(QCoreApplication.translate("Form", u"Text Size:", None))
        self.Text_size.setItemText(0, QCoreApplication.translate("Form", u"16", None))
        self.Text_size.setItemText(1, QCoreApplication.translate("Form", u"18", None))
        self.Text_size.setItemText(2, QCoreApplication.translate("Form", u"20", None))
        self.Text_size.setItemText(3, QCoreApplication.translate("Form", u"22", None))
        self.Text_size.setItemText(4, QCoreApplication.translate("Form", u"24", None))
        self.Text_size.setItemText(5, QCoreApplication.translate("Form", u"26", None))
        self.Text_size.setItemText(6, QCoreApplication.translate("Form", u"28", None))
        self.Text_size.setItemText(7, QCoreApplication.translate("Form", u"30", None))
        self.Text_size.setItemText(8, QCoreApplication.translate("Form", u"32", None))
        self.Text_size.setItemText(9, QCoreApplication.translate("Form", u"36", None))
        self.Text_size.setItemText(10, QCoreApplication.translate("Form", u"40", None))
        self.Text_size.setItemText(11, QCoreApplication.translate("Form", u"44", None))
        self.Text_size.setItemText(12, QCoreApplication.translate("Form", u"48", None))
        self.Text_size.setItemText(13, QCoreApplication.translate("Form", u"52", None))
        self.Text_size.setItemText(14, QCoreApplication.translate("Form", u"56", None))
        self.Text_size.setItemText(15, QCoreApplication.translate("Form", u"60", None))

        self.host.setText(QCoreApplication.translate("Form", u"Host:", None))
        self.Resolutionlab.setText(QCoreApplication.translate("Form", u"Resolution:", None))
        self.resolutioncomboBox.setItemText(0, QCoreApplication.translate("Form", u"1920 x 1080", None))
        self.resolutioncomboBox.setItemText(1, QCoreApplication.translate("Form", u"1600 x 900", None))
        self.resolutioncomboBox.setItemText(2, QCoreApplication.translate("Form", u"1366 x 768", None))
        self.resolutioncomboBox.setItemText(3, QCoreApplication.translate("Form", u"1280 x 720", None))
        self.resolutioncomboBox.setItemText(4, QCoreApplication.translate("Form", u"800 x 600", None))

        self.setcountryGMT.setText(QCoreApplication.translate("Form", u"Country:", None))
        self.SystemDate.setText(QCoreApplication.translate("Form", u"System Date: ", None))
        self.setpassword.setText(QCoreApplication.translate("Form", u"Set User Password: ", None))
        self.Systemtime.setText(QCoreApplication.translate("Form", u"System Time: ", None))
        self.SystemMemory.setText(QCoreApplication.translate("Form", u"System Memory: ", None))
        self.Port.setText(QCoreApplication.translate("Form", u"Port:", None))
        self.version_label.setText("")
        self.titlelabel.setText("")
        self.author_label.setText("")
        self.info_label.setText("")
    # retranslateUi

