pip install pyvistaqt
pip install ifcopenshell
pip install vtk
pip install PyQt5
pip install multiprocess
pip install pyqtgraph
pip install OpenGL
pip install numpy-stl
pip install meshio
pip install openpxyl
pip install pandas 
pip install serial
pip install tzlocal
pip install psutil
pip install netifaces
pip install numpy 
pip install fiona
pip install geopandas