pip install pyvistaqt
pip install ifcopenshell
pip install vtk
pip install PyQt5
pip install multiprocess
pip install pyqtgraph
pip install OpenGL
pip install numpy-stl
pip install meshio
pip install openxyl
pip install pandas 
