// Generated by gencpp from file my_robot_wallinterfaces/FileExtractionMessage.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_WALLINTERFACES_MESSAGE_FILEEXTRACTIONMESSAGE_H
#define MY_ROBOT_WALLINTERFACES_MESSAGE_FILEEXTRACTIONMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_wallinterfaces
{
template <class ContainerAllocator>
struct FileExtractionMessage_
{
  typedef FileExtractionMessage_<ContainerAllocator> Type;

  FileExtractionMessage_()
    : directory()
    , excelfile()  {
    }
  FileExtractionMessage_(const ContainerAllocator& _alloc)
    : directory(_alloc)
    , excelfile(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _directory_type;
  _directory_type directory;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _excelfile_type;
  _excelfile_type excelfile;





  typedef boost::shared_ptr< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> const> ConstPtr;

}; // struct FileExtractionMessage_

typedef ::my_robot_wallinterfaces::FileExtractionMessage_<std::allocator<void> > FileExtractionMessage;

typedef boost::shared_ptr< ::my_robot_wallinterfaces::FileExtractionMessage > FileExtractionMessagePtr;
typedef boost::shared_ptr< ::my_robot_wallinterfaces::FileExtractionMessage const> FileExtractionMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator1> & lhs, const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator2> & rhs)
{
  return lhs.directory == rhs.directory &&
    lhs.excelfile == rhs.excelfile;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator1> & lhs, const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_wallinterfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d217064ce75170f28ac78f629dbe4223";
  }

  static const char* value(const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd217064ce75170f2ULL;
  static const uint64_t static_value2 = 0x8ac78f629dbe4223ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_wallinterfaces/FileExtractionMessage";
  }

  static const char* value(const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string directory\n"
"string excelfile\n"
;
  }

  static const char* value(const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.directory);
      stream.next(m.excelfile);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FileExtractionMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_wallinterfaces::FileExtractionMessage_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "directory: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.directory);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "excelfile: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.excelfile);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_WALLINTERFACES_MESSAGE_FILEEXTRACTIONMESSAGE_H
