// Generated by gencpp from file my_robot_wallinterfaces/jointvaluesextract.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_WALLINTERFACES_MESSAGE_JOINTVALUESEXTRACT_H
#define MY_ROBOT_WALLINTERFACES_MESSAGE_JOINTVALUESEXTRACT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_wallinterfaces
{
template <class ContainerAllocator>
struct jointvaluesextract_
{
  typedef jointvaluesextract_<ContainerAllocator> Type;

  jointvaluesextract_()
    : joint_values()
    , placementcoord()  {
    }
  jointvaluesextract_(const ContainerAllocator& _alloc)
    : joint_values(_alloc)
    , placementcoord(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_values_type;
  _joint_values_type joint_values;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _placementcoord_type;
  _placementcoord_type placementcoord;





  typedef boost::shared_ptr< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> const> ConstPtr;

}; // struct jointvaluesextract_

typedef ::my_robot_wallinterfaces::jointvaluesextract_<std::allocator<void> > jointvaluesextract;

typedef boost::shared_ptr< ::my_robot_wallinterfaces::jointvaluesextract > jointvaluesextractPtr;
typedef boost::shared_ptr< ::my_robot_wallinterfaces::jointvaluesextract const> jointvaluesextractConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator1> & lhs, const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator2> & rhs)
{
  return lhs.joint_values == rhs.joint_values &&
    lhs.placementcoord == rhs.placementcoord;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator1> & lhs, const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_wallinterfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bde6b642b6d906e5d1da1cf7db201cda";
  }

  static const char* value(const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbde6b642b6d906e5ULL;
  static const uint64_t static_value2 = 0xd1da1cf7db201cdaULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_wallinterfaces/jointvaluesextract";
  }

  static const char* value(const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_values\n"
"int32[] placementcoord\n"
;
  }

  static const char* value(const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_values);
      stream.next(m.placementcoord);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointvaluesextract_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_wallinterfaces::jointvaluesextract_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_values: ";
    if (v.joint_values.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_values.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_values[i]);
    }
    if (v.joint_values.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "placementcoord: ";
    if (v.placementcoord.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.placementcoord.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.placementcoord[i]);
    }
    if (v.placementcoord.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_WALLINTERFACES_MESSAGE_JOINTVALUESEXTRACT_H
