# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MokZhiZhuan\OneDrive - WINSYS TECHNOLOGY PTE LTD\Desktop\Greyform\Python_Application\UI_Design\Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 300)
        self.profileiconlabel = QtWidgets.QLabel(Form)
        self.profileiconlabel.setGeometry(QtCore.QRect(110, 0, 111, 101))
        self.profileiconlabel.setText("")
        self.profileiconlabel.setPixmap(QtGui.QPixmap("c:\\Users\\MokZhiZhuan\\OneDrive - WINSYS TECHNOLOGY PTE LTD\\Desktop\\Greyform\\Python_Application\\UI_Design\\—Pngtree—avatar icon profile icon member_5247852.png"))
        self.profileiconlabel.setScaledContents(True)
        self.profileiconlabel.setObjectName("profileiconlabel")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 100, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.userlabel = QtWidgets.QLabel(Form)
        self.userlabel.setGeometry(QtCore.QRect(70, 130, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.userlabel.setFont(font)
        self.userlabel.setText("")
        self.userlabel.setObjectName("userlabel")
        self.loginbutton = QtWidgets.QPushButton(Form)
        self.loginbutton.setGeometry(QtCore.QRect(100, 230, 121, 25))
        self.loginbutton.setObjectName("loginbutton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Welcome"))
        self.loginbutton.setText(_translate("Form", "Back To Login"))
