// Generated by gencpp from file my_robot_wallinterfaces/SetLed.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_WALLINTERFACES_MESSAGE_SETLED_H
#define MY_ROBOT_WALLINTERFACES_MESSAGE_SETLED_H

#include <ros/service_traits.h>


#include <my_robot_wallinterfaces/SetLedRequest.h>
#include <my_robot_wallinterfaces/SetLedResponse.h>


namespace my_robot_wallinterfaces
{

struct SetLed
{

typedef SetLedRequest Request;
typedef SetLedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLed
} // namespace my_robot_wallinterfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_wallinterfaces::SetLed > {
  static const char* value()
  {
    return "c392f71e5178d9c3ca2a5905cf219411";
  }

  static const char* value(const ::my_robot_wallinterfaces::SetLed&) { return value(); }
};

template<>
struct DataType< ::my_robot_wallinterfaces::SetLed > {
  static const char* value()
  {
    return "my_robot_wallinterfaces/SetLed";
  }

  static const char* value(const ::my_robot_wallinterfaces::SetLed&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_wallinterfaces::SetLedRequest> should match
// service_traits::MD5Sum< ::my_robot_wallinterfaces::SetLed >
template<>
struct MD5Sum< ::my_robot_wallinterfaces::SetLedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_wallinterfaces::SetLed >::value();
  }
  static const char* value(const ::my_robot_wallinterfaces::SetLedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_wallinterfaces::SetLedRequest> should match
// service_traits::DataType< ::my_robot_wallinterfaces::SetLed >
template<>
struct DataType< ::my_robot_wallinterfaces::SetLedRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_wallinterfaces::SetLed >::value();
  }
  static const char* value(const ::my_robot_wallinterfaces::SetLedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_wallinterfaces::SetLedResponse> should match
// service_traits::MD5Sum< ::my_robot_wallinterfaces::SetLed >
template<>
struct MD5Sum< ::my_robot_wallinterfaces::SetLedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_wallinterfaces::SetLed >::value();
  }
  static const char* value(const ::my_robot_wallinterfaces::SetLedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_wallinterfaces::SetLedResponse> should match
// service_traits::DataType< ::my_robot_wallinterfaces::SetLed >
template<>
struct DataType< ::my_robot_wallinterfaces::SetLedResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_wallinterfaces::SetLed >::value();
  }
  static const char* value(const ::my_robot_wallinterfaces::SetLedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_WALLINTERFACES_MESSAGE_SETLED_H
